# Site settings
title: Thomas Marsland
twitter_username: tmarsland
name: Thomas Marsland

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: https://medium.com/@tmarsland_13763
 - title: GitHub
   url: https://github.com/ActualTom
# - title: StackOverflow
#   url: https://stackoverflow.com/users/258813/rhinds
# - title: DZone
#   url: https://dzone.com/users/899489/rhinds.html
 - title: LinkedIn
   url: https://www.linkedin.com/in/thomas-marsland
 - title: VetSec
   url: https://www.veteransec.org/

#Any buzzword skills you want to include
skills:
 - Strategic Planning & Implementation
 - Resource Allocation & Optimization
 - Process Improvement Initiatives
 - Project & Program Management
 - Stakeholder Relationship Management
 - Problem Solving & Crisis Management
 - Implementation Strategies
 - Sraff Training & Development
 - Advanced Technology Research
 - Collaborative Approach
 - IT Operations Leadership
 - VMWare Architecture
 - Google Cloud
 - Technical Architecture
 - Machine learning

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: https://medium.com/@tmarsland_13763

#Work experience is required
roles:
 - title: VP of Technology & Technical Services
   start: 2022
   end: Ongoing
   employer: Cloud Range
   description: Instrumental in leading technical operations for a start-up company that provides training to a wide range of clients on Digital Forensics and cybersecurity incident response.  Oversee all range virtualization infrastructure, network access, identity management, technical pre-sales, learning management system, and cybersecurity learning content development.  Supervise seven direct reports along with a technical team, assess performance, identify skill gaps, evaluate training needs, and conduct training sessions to improve productivity and efficiency.
 - title: Board Chairman
   start: 2020
   end: Ongoing
   employer: VetSec
   description: VetSec is a 501c3 non-profit that seeks to create a world where no veteran pursuing a career in cybersecurity goes unemployed. As the CEO and Board Chairman, I worked to develop a long-term mentorship program, formalized the annual get-together into a cybersecurity conference (VetSecCon), raised the membership from ~1,800 to over 6,600, and worked with a large number of companies to provide funding, training, discounts, and employment for veterans.
 - title: Senior Program Manager
   start: 2001
   end: 2023
   employer: US Navy
   description: I served in numerous roles in my 22 years in the United States Navy, most recently as a Senior Program Manager - providing oversight to three nuclear powered submarines and their enginerooms.  Previously, as an IT Director, I administered three networks of varying classifications for 500 staff and over 3000 students, while supervising a team of five for the Navy Nuclear Power Training Command.
 
#Education is required
education:
 - level: Master of Science (M.S.)
   date: 2022
   subject: Cybersecurity
   school: University of Charleston
 - level: Bachelor of Science (B.S.)
   date: 2016
   subject: Information Technology - Security Emphasis
   school: Western Governors University

#This section is optional (as is the image link below)
#coursera:
#   profileurl: https://www.coursera.org/user/i/c6362b4056f755a04bef6a791a62102b
#   courses:
#    - title: Functional Programming Principles in Scala
#      link: https://www.coursera.org/course/progfun
#      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
#      date: September 16, 2013
#    - title: Algorithms Design and Analysis, Part 1
#      link: https://www.coursera.org/specializations/algorithms
#      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
#      date: April 28, 2014

#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute
#speakerdeck:
#   profileurl: https://speakerdeck.com/robhinds
#   talks:
#    - title: Product Management for Engineers
#      speakerdeckId: 94f0070c4e434ec79fe9b4eb2cb574e0
#      conference: API Conference, Berlin 2018
#    - title: Agile Machine Learning - from Theory to Production
#      speakerdeckId: ec84f2f56e9743afb0675b1eeeb6b6ce
#      conference: W-JAX Conference, Munich 2017 (London 2017)

#List of interesting Github repo/projects to include - optional
github:
 - actualtom/actualtom.github.io
 - actualtom/PyFloodMap
 - actualtom/crc-uptime
 - acutaltom/Cyber-KST-Project
 
#Stackoverflow flair is optional
#stackoverflow:
 #  profileurl: https://stackoverflow.com/users/258813/rhinds
  # flairimageurl: https://stackoverflow.com/users/flair/258813.png

intro: |
  I am a technology leader with over 20 years experience. I have worked in a variety of roles, from working on an IT Helpdesk to managing one, to working as a network architect and systems administrator. I worked in the US Navy as a Director of IT for a schoolhouse that served over 3,500 combined staff and students, and currently am the VP of Technology for Cloud Range, a cybersecurity company that provides realistic live-fire attack scenarios on our own customizable cyber ranges.<br/><br/>
  I enjoy building not only with technology, like cyber ranges, but I really enjoy building processes that work - bringing order to chaos, and establishing 'systems' and programs.  I see the bigger picture, communicate across cross-functional teams, and "get stuff done."  I focus on first-time quality while also meeting the business needs on time.<br/><br/>
  In my free time, I enjoy time with my family, taking care of our acreage and home, and backpacking throughout the wilderness of the Pacific Northwest.  I currently work as the VP of Technology for Cloud Range, where we train teams globally on cybersecurity incident response, as well as the Board Chair for VetSec, a 501c3 that works to help veterans find meaningful employment in cybersecurity.  At Cloud Range, I am instrumental in leading technical operations for a start-up company that provides training to a wide range of clients on Digital Forensics and cybersecurity incident response.  Oversee all range virtualization infrastructure, network access, identity management, technical pre-sales, learning management system, and cybersecurity learning content development.  I supervise seven direct reports along with a technical team, assess performance, identify skill gaps, evaluate training needs, and conduct training sessions to improve productivity and efficiency.

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>Publications</strong>: Through both my work in VetSec and in Cloud Range, I've been fortunate enough to have been published in numerous locations.  Below is a summary of articles:<br/><br/>
   <a href="https://www.industryweek.com/technology-and-iiot/cybersecurity/article/21283123/international-cybersecurity-operation-takes-down-russian-cybercriminal-gang">International Cybersecurity Operation Takes Down Russian Cybercriminal Gang</a> : February 20th, 2024<br/><br/>
   <a href="https://industrialcyber.co/utilities-energy-power-water-waste/veolia-north-america-and-southern-water-hit-by-ransomware-attacks-data-breach-concerns-arise/">Veolia North America and Southern Water hit by ransomware attacks, data breach concerns arise</a> : January 25th, 2024<br/><br/>
   <a href="https://www.industryweek.com/technology-and-iiot/cybersecurity/article/21280525/cybersecurity-concerns-for-manufacturers-in-2024">Cybersecurity Concerns for Manufacturers in 2024</a> : January 16th, 2024<br/><br/>
   <a href="https://itnerd.blog/2023/12/29/2024-predictions-from-leading-cybersecurity-experts/">2-24 Predictions From Leading Cybersecurity Experts</a> : December 29th, 2023<br/><br/>
   <a href="https://itnerd.blog/2023/12/01/north-texas-municipal-water-district-pwned-in-a-ransomware-attack/">North Texas Municipal Water District Pwned In A Ransomware Attack</a> : December 1, 2023<br/><br/>
   <a href="https://vmblog.com/archive/2023/10/18/cloud-range-2024-predictions-the-evolution-of-cybersecurity-in-2024-a-shift-towards-human-centric-defense.aspx">The Evolution of Cybersecurity in 2024 - A Shift Towards Human-Centric Defense</a> : October 28th, 2024<br/><br/>
   <a href="https://thecyberwire.com/stories/396cc81c68d048b8b472b84bbae665c5/improving-security-for-open-source-ics-software">Improving security for open-source ICS software</a> : October 13th, 2023<br/><br/>
   <a href="https://thecyberwire.com/stories/8a7a02340ab34a13b672a6c41c3b8b45/us-federal-shutdown-averted-or-postponed-effects-on-cybersecurity">US Federal shutdown averted (or postponed): effects on cybersecurity</a> : September 20th, 2023<br/><br/>
   <a href="https://www.darkreading.com/operations/fortinet-announces-formation-of-veterans-program-advisory-council-to-narrow-the-cybersecurity-skills-gap-with-military-veteran-talent">Fortinet Announces Formation of Veterans Program Advisory Council to Narrow the Cybersecurity Skills Gap With Military Veteran Talent</a> : September 27th, 2023<br/><br/>
   <a href="https://thecyberwire.com/stories/25688d912ff747d9bc0f966a8be11648/university-of-michigan-overcomes-cyberattack-that-delayed-the-academic-year">University of Michigan overcomes cyberattack that delayed the academic year</a> :  August 30th, 2023<br/><br/>
   <a href="https://thecyberwire.com/stories/52fd882ae7f243e1a7f0aa6943f2b41a/patch-tuesday-retrospective-july-2023">Patch Tuesday retrospective: July 2023</a> : July 13th, 2023<br/><br/>
   <a href="https://www.esecurityplanet.com/threats/romcom-exploit/">Microsoft Patch Tuesday Addresses 130 Flaws - Including Unpatched RomCom Exploit</a> : July 12th, 2023<br/><br/>
   <a href="https://www.smartindustry.com/benefits-of-transformation/cybersecurity/blog/33006957/toughen-up-the-value-of-a-robust-vulnerabilitymanagement-program">Toughen up! The value of a robust vulnerability-management program</a> : June 21st, 2023<br/><br/>
   <a href="https://www.bnnbloomberg.ca/a-zero-day-flaw-in-hacked-moveit-software-was-exposed-on-twitter-1.1935113">A Zero-Day Flaw in Hacked MOVEit Software Was Exposed on Twitter</a> : June 19th, 2023<br/><br/>
   <a href="http://web.archive.org/web/20230616184225/https://www.msspalert.com/cybersecurity-breaches-and-attacks/ransomware/russian-cl0p-operatives-hit-u-s-federal-agencies-in-widespread-cyberattack/">Russian Cl0p Operatives Hit U.S. Federal Agencies in Widespread Cyberattack</a> : June 16th, 2023<br/><br/>
   <a href="https://www.isssource.com/moveit-breaches-growing/">MOVEit Breaches Growing</a> : June 16th, 2023<br/><br/>
   <a href="https://industrialcyber.co/news/us-government-agencies-struck-by-cyber-attack-as-clop-hackers-likely-exploited-moveit-software-vulnerability/">US government agencies struck by cyber attack, as Clop hackers likely exploited MOVEit software vulnerability</a> : June 16th, 2023<br/><br/>
   <a href="https://www.utilitydive.com/news/doe-among-federal-agencies-hit-by-possible-russian-cyberattack/653216/">DOE among federal agencies hit by possible Russian cyberattack</a> : June 16th, 2023<br/><br/>
   <br/>
   <strong>Skills</strong>: I have a good knowledge of application life-cycle management. I have built range networks from the ground up, directly influencing the UI/UX and experience, as well as the architecture, on Google Cloud and VMWare.  As I stated above, I enjoy seeing the bigger picture, communicating across the various business units, creating order out of chaos, and getting stuff done.  Thanks for tuning in and checking this out!
